# Generated by Django 5.1.3 on 2025-06-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_alter_ticket_turno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="turno",
            field=models.CharField(
                choices=[("MANHA", "Manhã"), ("NOITE", "Noite")],
                max_length=10,
                verbose_name="Turno",
            ),
        ),
    ]
