# Generated by Django 5.1.3 on 2025-03-18 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessao', models.CharField(max_length=255, unique=True)),
                ('pesquisador', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=100)),
                ('ponto', models.CharField(max_length=255)),
                ('horario_inicio', models.TimeField()),
                ('data', models.DateField()),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Counting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veiculo', models.CharField(max_length=255)),
                ('movimento', models.CharField(max_length=255)),
                ('contagem', models.IntegerField()),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contagens', to='contagens.session')),
            ],
        ),
    ]
