# Generated by Django 5.1.3 on 2025-03-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contagens', '0003_alter_session_criado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
