# Generated by Django 5.1.3 on 2025-03-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contagens', '0004_alter_session_horario_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
