# Generated by Django 5.1.3 on 2025-03-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contagens', '0005_alter_session_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='data',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='horario_inicio',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
