# Generated by Django 5.1.3 on 2025-03-23 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contagens', '0007_session_movimentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='movimentos',
        ),
    ]
