# Generated by Django 5.1.3 on 2025-03-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contagens', '0008_remove_session_movimentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='movimentos',
            field=models.JSONField(default=list),
        ),
    ]
