# Generated by Django 5.1.3 on 2025-03-25 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contagens', '0009_session_movimentos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counting',
            options={'ordering': ['periodo', 'id']},
        ),
        migrations.AddField(
            model_name='counting',
            name='periodo',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='counting',
            name='contagem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='counting',
            name='movimento',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='counting',
            name='sessao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contagens.session'),
        ),
        migrations.AlterField(
            model_name='counting',
            name='veiculo',
            field=models.CharField(max_length=100),
        ),
    ]
