# Generated by Django 5.1.3 on 2025-04-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contagens', '0011_session_created_at_session_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='padrao',
            field=models.CharField(blank=True, help_text='Tipo de padrão utilizado na contagem', max_length=100, null=True),
        ),
    ]
