# Generated by Django 5.1.3 on 2025-04-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contagens', '0012_session_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('ES', 'Em Separação'), ('EA', 'Em Andamento'), ('CO', 'Concluído'), ('PA', 'Parado')], default='ES', max_length=2),
        ),
    ]
