# Generated by Django 5.1.3 on 2025-04-11 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contagens', '0013_session_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='status',
        ),
    ]
