# Generated by Django 5.1.3 on 2025-07-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contagens", "0017_data_status_migracao"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="session",
            name="contagens_s_respons_738bbe_idx",
        ),
        migrations.RemoveField(
            model_name="session",
            name="responsavel",
        ),
        migrations.AddField(
            model_name="session",
            name="horario_fim",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
