# Generated by Django 5.1.3 on 2025-02-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='setor',
            field=models.CharField(choices=[('CON', 'Contagem'), ('DIG', 'Digitação'), ('P&D', 'Perci'), ('SUPER', 'Supervisao')], default='CON', max_length=5),
        ),
    ]
