# Generated by Django 5.1.3 on 2025-03-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_user_preferences_alter_user_setor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='padraocontagem',
            old_name='tipo_do_padrao',
            new_name='pattern_type',
        ),
        migrations.RenameField(
            model_name='userpadraocontagem',
            old_name='tipo_do_padrao',
            new_name='pattern_type',
        ),
        migrations.AlterUniqueTogether(
            name='userpadraocontagem',
            unique_together={('user', 'pattern_type', 'veiculo')},
        ),
    ]
