# Generated by Django 5.1.3 on 2025-03-14 19:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_rename_tipo_do_padrao_padraocontagem_pattern_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='padraocontagem',
            options={'verbose_name': 'Padrão de Contagem', 'verbose_name_plural': 'Padrões de Contagem'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelOptions(
            name='userpadraocontagem',
            options={'verbose_name': 'Usuário Padrão de Contagem', 'verbose_name_plural': 'Usuários Padrão de Contagem'},
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('details', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Counting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=100)),
                ('movement', models.CharField(max_length=100)),
                ('count_total', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.session')),
            ],
        ),
    ]
