# Generated by Django 5.1.3 on 2025-03-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0004_alter_padraocontagem_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='user',
        ),
        migrations.DeleteModel(
            name='Counting',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
