# Generated by Django 5.1.3 on 2025-03-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0005_remove_session_user_delete_counting_delete_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PadraoContagem',
        ),
        migrations.DeleteModel(
            name='UserPadraoContagem',
        ),
    ]
