# Generated by Django 5.1.3 on 2025-07-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autenticacao", "0006_delete_padraocontagem_delete_userpadraocontagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="setor",
            field=models.CharField(
                choices=[
                    ("CON", "Contagem"),
                    ("DIG", "Digitação"),
                    ("P&D", "Perci"),
                    ("SUPER", "Supervisao"),
                    ("ENG", "Engenharia"),
                    ("ADM", "Administrativo"),
                ],
                default="CON",
                max_length=5,
            ),
        ),
    ]
