# Generated by Django 5.1.3 on 2025-03-25 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PadraoContagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(default='padrao_perplan', max_length=100, verbose_name='Tipo do Padrão')),
                ('veiculo', models.CharField(max_length=100, verbose_name='Veículo')),
                ('bind', models.CharField(max_length=50, verbose_name='Bind')),
            ],
            options={
                'verbose_name': 'Padrão de Contagem',
                'verbose_name_plural': 'Padrões de Contagem',
            },
        ),
        migrations.CreateModel(
            name='UserPadraoContagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(default='padrao_perplan', max_length=100)),
                ('veiculo', models.CharField(max_length=100, verbose_name='Veículo')),
                ('bind', models.CharField(max_length=50, verbose_name='Bind')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binds_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário Padrão de Contagem',
                'verbose_name_plural': 'Usuários Padrão de Contagem',
                'unique_together': {('user', 'pattern_type', 'veiculo')},
            },
        ),
    ]
