# Generated by Django 5.1.3 on 2025-04-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='padraocontagem',
            options={'ordering': ['pattern_type', 'order', 'id'], 'verbose_name': 'Padrão de Contagem', 'verbose_name_plural': 'Padrões de Contagem'},
        ),
        migrations.AddField(
            model_name='padraocontagem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
    ]
