# Generated by Django 5.1.3 on 2025-08-13 02:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contagens", "0018_remove_session_contagens_s_respons_738bbe_idx_and_more"),
        ("trabalhos", "0003_alter_ponto_localizacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_hora",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Valor por Hora",
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        choices=[
                            ("funcionario", "Funcionário"),
                            ("supervisor", "Supervisor"),
                        ],
                        default="funcionario",
                        max_length=20,
                        verbose_name="Cargo",
                    ),
                ),
                (
                    "departamento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Departamento"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "data_admissao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Admissão"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folha_ponto_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuário",
                "verbose_name_plural": "Perfis de Usuários",
            },
        ),
        migrations.CreateModel(
            name="WorkCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "codigo_trabalho",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_codes",
                        to="trabalhos.codigo",
                        verbose_name="Código do Trabalho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Código de Trabalho",
                "verbose_name_plural": "Códigos de Trabalho",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField(verbose_name="Ano")),
                (
                    "mes",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Mês",
                    ),
                ),
                (
                    "horas_trabalhadas",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        verbose_name="Horas Trabalhadas",
                    ),
                ),
                (
                    "valor_hora",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Valor/Hora no Período",
                    ),
                ),
                (
                    "total_bruto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total Bruto"
                    ),
                ),
                (
                    "registros_aprovados",
                    models.IntegerField(default=0, verbose_name="Registros Aprovados"),
                ),
                (
                    "registros_pendentes",
                    models.IntegerField(default=0, verbose_name="Registros Pendentes"),
                ),
                ("data_calculo", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salaries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salário",
                "verbose_name_plural": "Salários",
                "ordering": ["-ano", "-mes", "user__username"],
                "unique_together": {("user", "ano", "mes")},
            },
        ),
        migrations.CreateModel(
            name="TimeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                ("entrada1", models.TimeField(verbose_name="Entrada 1")),
                ("saida1", models.TimeField(verbose_name="Saída 1")),
                (
                    "entrada2",
                    models.TimeField(blank=True, null=True, verbose_name="Entrada 2"),
                ),
                (
                    "saida2",
                    models.TimeField(blank=True, null=True, verbose_name="Saída 2"),
                ),
                (
                    "entrada3",
                    models.TimeField(blank=True, null=True, verbose_name="Entrada 3"),
                ),
                (
                    "saida3",
                    models.TimeField(blank=True, null=True, verbose_name="Saída 3"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovado", "Aprovado"),
                            ("rejeitado", "Rejeitado"),
                        ],
                        default="pendente",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_aprovacao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Aprovação"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aprovado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aprovacoes_time_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprovado por",
                    ),
                ),
                (
                    "sessao_contagem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="time_records",
                        to="contagens.session",
                        verbose_name="Sessão de Contagem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
                (
                    "work_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="folha_ponto.workcode",
                        verbose_name="Código de Trabalho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Ponto",
                "verbose_name_plural": "Registros de Ponto",
                "ordering": ["-data", "user__username"],
                "indexes": [
                    models.Index(
                        fields=["user", "data"], name="folha_ponto_user_id_cf9126_idx"
                    ),
                    models.Index(fields=["data"], name="folha_ponto_data_752f5c_idx"),
                    models.Index(
                        fields=["status"], name="folha_ponto_status_c9706f_idx"
                    ),
                ],
                "unique_together": {("user", "data")},
            },
        ),
    ]
