# Generated by Django 5.1.3 on 2025-04-17 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('padroes', '0002_alter_padraocontagem_options_padraocontagem_order'),
        ('trabalhos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Croquis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=100)),
                ('movimento', models.CharField(max_length=100)),
                ('data_croqui', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('imagem', models.ImageField(upload_to='croquis/')),
                ('status', models.CharField(choices=[('A', 'Aprovado'), ('R', 'Reprovado'), ('P', 'Pendente')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('aprovado_por', models.ForeignKey(blank=True, db_column='aprovado_por', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='croquis_aprovados', to=settings.AUTH_USER_MODEL)),
                ('codigo', models.ForeignKey(db_column='codigo', on_delete=django.db.models.deletion.CASCADE, related_name='croquis', to='trabalhos.codigo')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='croquis_criados', to=settings.AUTH_USER_MODEL)),
                ('padrao', models.ForeignKey(db_column='padrao', on_delete=django.db.models.deletion.CASCADE, related_name='croquis', to='padroes.padraocontagem')),
                ('ponto', models.ForeignKey(db_column='ponto', on_delete=django.db.models.deletion.CASCADE, related_name='croquis', to='trabalhos.ponto')),
            ],
            options={
                'verbose_name': 'Croqui',
                'verbose_name_plural': 'Croquis',
                'db_table': 'croquis_croquis',
                'ordering': ['-created_at'],
            },
        ),
    ]
