# Generated by Django 5.1.3 on 2025-04-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croquis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='croquis',
            name='observacao',
            field=models.TextField(blank=True, help_text='Observações sobre o croqui', null=True),
        ),
        migrations.AlterModelTable(
            name='croquis',
            table='croquis',
        ),
    ]
