# Generated by Django 5.1.3 on 2025-04-17 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croquis', '0002_croquis_observacao_alter_croquis_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='croquis',
            name='hora_fim',
        ),
        migrations.RemoveField(
            model_name='croquis',
            name='hora_inicio',
        ),
        migrations.AlterField(
            model_name='croquis',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='croquis_aprovados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='croquis',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='croquis_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='croquis',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='croquis',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('R', 'Reprovado')], default='P', max_length=1),
        ),
        migrations.AlterModelTable(
            name='croquis',
            table=None,
        ),
    ]
