# Generated by Django 5.1.3 on 2025-04-17 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('croquis', '0003_remove_croquis_hora_fim_remove_croquis_hora_inicio_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='croquis',
            table='croquis',
        ),
    ]
