# Generated by Django 5.1.3 on 2025-04-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croquis', '0004_alter_croquis_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='croquis',
            name='hora_fim',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='croquis',
            name='hora_inicio',
            field=models.TimeField(null=True),
        ),
    ]
