# Generated by Django 5.1.3 on 2025-04-24 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimento', models.CharField(max_length=100)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='trabalhos.ponto')),
            ],
        ),
        migrations.CreateModel(
            name='PontoDetailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ponto_details/')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trabalhos.pontodetail')),
            ],
        ),
    ]
