# Generated by Django 5.1.3 on 2025-04-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trabalhos", "0002_pontodetail_pontodetailimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ponto",
            name="localizacao",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
